spring.application.name=backend

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/location_alarm_db
spring.datasource.username=your_username
spring.datasource.password=your_password

jwt.secret=your_secret_key_here